title: Tanveer Abdulaziz
author:
  name: Tanveer Abdulaziz
  email: tanveer.ismail40@gmail.com

description: >
  Cybersecurity Portfolio/Blog (CTFs, SOCs, and More!!)

# theme: minima
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - ctfs.md
  - socs.md
  - cyberdef.md
  - overthewire.md

minima:
  skin: auto

  social_links:
    - {platform: linkedin, user_url: "https://www.linkedin.com/in/tanveer-abdulaziz"}
    - {platform: github, user_url: "https://github.com/jekyll/minima"}
    
  
